// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkFmBuaHPvv6RaKIwpN_WamhCVO2oWAfA',
    appId: '1:556681422189:web:3b6f16821c081e9c082664',
    messagingSenderId: '556681422189',
    projectId: 'myekigai-47a59',
    authDomain: 'myekigai-47a59.firebaseapp.com',
    storageBucket: 'myekigai-47a59.appspot.com',
    measurementId: 'G-56YCS48FRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zLbMXCczEG4Bms0JBntpMXoUqEYnAYo',
    appId: '1:556681422189:android:2395a0f5f12a9218082664',
    messagingSenderId: '556681422189',
    projectId: 'myekigai-47a59',
    storageBucket: 'myekigai-47a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7-3537IxfACEW6uuue5wSjrawVsrLzFQ',
    appId: '1:556681422189:ios:534413f23b233fec082664',
    messagingSenderId: '556681422189',
    projectId: 'myekigai-47a59',
    storageBucket: 'myekigai-47a59.appspot.com',
    androidClientId: '556681422189-mttumjph391pkurelmu964srtboj487b.apps.googleusercontent.com',
    iosClientId: '556681422189-48h490954rusjkj6vrj3j6m91cuc03cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.myekigai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7-3537IxfACEW6uuue5wSjrawVsrLzFQ',
    appId: '1:556681422189:ios:f7c91a3121cf4d73082664',
    messagingSenderId: '556681422189',
    projectId: 'myekigai-47a59',
    storageBucket: 'myekigai-47a59.appspot.com',
    androidClientId: '556681422189-mttumjph391pkurelmu964srtboj487b.apps.googleusercontent.com',
    iosClientId: '556681422189-2pk5uhno1qbnefotnu15t1fiagbvnrod.apps.googleusercontent.com',
    iosBundleId: 'com.example.myekigai.RunnerTests',
  );
}
